github:
  auth_url: "https://github.com/login/oauth/authorize"
  validate_url: "https://github.com/login/oauth/access_token"
  user_api: "https://api.github.com/user"

  client_id: "Register your client on GitHub!"
  client_secret: "Register your client on GitHub!"
  redirect_uri: "https://example.com/auth-github"

cas:
  url: "https://passport.ustc.edu.cn/login"
  validate: "https://passport.ustc.edu.cn/serviceValidate"
  redirector: "http://home.ustc.edu.cn/~zzh1996/cas_redirect.html"
  logout: "https://passport.ustc.edu.cn/logout"

  redirect_uri: "https://example.com/auth-ustc"

session_key: "Secret for cookie signature"
session_expiry: 600
token_key: "Secret for token signature"
# Note: No token expiry
